version: 2.1

#
# Variables
#

project_directory: &project_directory ~/project

#
# Jobs
#

jobs:
  test:
    working_directory: *project_directory
    resource_class: macos.m1.medium.gen1
    macos:
      xcode: "16.0.0"
    steps:
      - checkout
      - run:
          name: Test
          command: |
            set -o pipefail && xcodebuild -project LoopKit.xcodeproj -scheme Shared build -destination 'name=iPhone 16' test | xcpretty
      - store_test_results:
          path: test_output
#
# Workflows
#

workflows:
  version: 2.1
  build_and_test:
    jobs:
      - test
