version: 2.1

#
# Variables
#

project_directory: &project_directory ~/project

#
# Jobs
#

jobs:
  test:
    working_directory: *project_directory
    macos:
      xcode: 11.5.0
    resource_class: large # Uses the "large" macOS executor
    steps:
      - checkout
      - run:
          name: Test
          command: |
            set -o pipefail && xcodebuild -project LoopKit.xcodeproj -scheme Shared build -destination 'name=iPhone 8' test | xcpretty
      - store_test_results:
          path: test_output

  build-example:
    working_directory: *project_directory
    macos:
      xcode: 11.5.0
    resource_class: large # Uses the "large" macOS executor
    steps:
      - checkout
      - run:
          name: Test
          command: |
            set -o pipefail && xcodebuild -project LoopKit.xcodeproj -scheme "LoopKit Example" build -destination 'name=iPhone 8' CODE_SIGNING_ALLOWED=NO | xcpretty
      - store_test_results:
          path: test_output

#
# Workflows
#

workflows:
  version: 2.1
  build_and_test_Tidepool:
    jobs:
      - test
      - build-example
